### PR TITLE
Test py38 and py37

### PR DESCRIPTION
**Pull request by ocefpaf**
We could keep testing on py36 but I don't think it is worth it.

### CODE REVIEW

**Comment by efiring** [comment]
We should also drop 2.7.

**Comment by ocefpaf** [comment]
> We should also drop 2.7.

Done! I don't think we have any 2.7 specific code to remove though.

**Comment by efiring** [comment]
There are a bunch of "from __future__ import" lines, but they could be removed later, unless you want to sweep them out as part of this PR.

```
./utide/constituent_selection.py:from __future__ import (absolute_import, division, print_function)
./utide/ellipse_params.py:from __future__ import (absolute_import, division, print_function)
./utide/confidence.py:from __future__ import (absolute_import, division, print_function)
./utide/periodogram.py:from __future__ import (absolute_import, division, print_function)
./utide/diagnostics.py:from __future__ import (absolute_import, division, print_function)
./utide/robustfit.py:from __future__ import (absolute_import, division, print_function)
./utide/__init__.py:from __future__ import (absolute_import, division, print_function)
./utide/_solve.py:from __future__ import (absolute_import, division, print_function)
./utide/_time_conversion.py:from __future__ import (absolute_import, division, print_function)
./utide/_ut_constants.py:from __future__ import (absolute_import, division, print_function)
./utide/harmonics.py:from __future__ import (absolute_import, division, print_function)
./utide/utilities.py:from __future__ import (absolute_import, division, print_function)
./utide/_reconstruct.py:from __future__ import (absolute_import, division, print_function)
./utide/data/mat2npz.py:from __future__ import (absolute_import, division, print_function)
./utide/astronomy.py:from __future__ import (absolute_import, division, print_function)
./tests/test_astron.py:from __future__ import (absolute_import, division, print_function)
./tests/test_solve.py:from __future__ import (absolute_import, division, print_function)
./tests/test_harmonics.py:from __future__ import (absolute_import, division, print_function)
./tests/test_periodogram.py:from __future__ import (absolute_import, division, print_function)
./tests/test_normalize.py:from __future__ import (absolute_import, division, print_function)
./versioneer.py:from __future__ import print_function
```

**Comment by ocefpaf** [comment]
Indeed. Fixing those now...

**Comment by efiring** [comment]
Thank you, @ocefpaf.

**Pull request merged**
