### PR TITLE
Minor bug fix.

### PR DESCRIPTION
**Pull request by ocefpaf**
I am not sure if the code is doing the right thing there, but I found this bug while experimenting with the available options.

### CODE REVIEW

**Comment by efiring** [comment]
Good catch.  Not so minor...

**Comment by ocefpaf** [comment]
I need to invest some time in writing the tests...

BTW: I found that while writing this notebook

http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ocefpaf/6e41bea12ed360727700/raw/c3a57115ecd270ea165b0c6afb5903948925dda8/tri_tide_movie.ipynb

That got me thinking that maybe it is worth mentioning `FUV ` in the docs.

**Comment by efiring** [comment]
Nice example, thank you! 

Yes, adding other internal components to the docs is what I had in mind; but I want to do some API cleanup and pythonization along the way.  That `nflgs`, for example, has to go!  And I would like to get rid of the assumption that times are matlab datenums.  An epoch will be added at the top level.  It could be carried along down into some of the internal functions, at minimal cost.

**Comment by ocefpaf** [comment]
:+1: to all that!!!

**Pull request merged**
