### PR TITLE
GHA take2

### PR DESCRIPTION
**Pull request by ocefpaf**
This moves the package publication to GitHub Actions. But it is not ready to be merged yet!

We need to add a PyPI token as a GH secret and I do not have the permissions to do so in this repo.
@wesleybowman can you add the token or give some of us permission to do it? We'll need it again when I move the documentation builds to GH Actions.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I converted this to a draft until we can set the tokens up.

**Comment by wesleybowman** [comment]
@ocefpaf I've added `PYPI_PASSWORD` to the Repo's secrets

Sorry for the delay, been a busy week.

**Comment by ocefpaf** [comment]
> @ocefpaf I've added `PYPI_PASSWORD` to the Repo's secrets

Awesome! Thanks!!
 
> Sorry for the delay, been a busy week.

Don't worry. There is no hurry at all. Just want to tidy things up a bit for future proof our CI.

**Review by efiring — APPROVED** [review]
Looks plausible--I think I see roughly what is going on.  Let's try it.  Merge when ready.

**Pull request merged**
