### PR TITLE
Clean up reconstruct, add explicit kwargs, smoke tests

### PR DESCRIPTION
**Pull request by efiring**

### CODE REVIEW

**Comment by efiring** [comment]
The failures here are all PEP8, and I suspect most, if not all, will go away after the PR before this one is merged.  Let's retest then.

**Comment by wesleybowman** [comment]
I reran the tests, Travis still fails after the merge, but I agree that it's only PEP type errors. The 13 tests for the actual code pass.

**Comment by wesleybowman** [comment]
@ocefpaf this looks fine, correct?

**Comment by ocefpaf** [comment]
> @ocefpaf this looks fine, correct?

Yes. Merge away :smile: 

I separated the tests in #42 and `pep8` no longer results in failing test. So we can merge good code faster, and worried about coding standards later.

**Comment by wesleybowman** [comment]
👍

**Pull request merged**
