### PR TITLE
Update Travis-CI config

### PR DESCRIPTION
**Pull request by ocefpaf**
@efiring this should do it.

### CODE REVIEW

**Comment by efiring** [comment]
Nice!  Thank you!

**Comment by ocefpaf** [comment]
> Nice! Thank you!

Thank you for the code improvements! I can only help with boilerplate stuff like this.

**Comment by wesleybowman** [comment]
Am I good to merge here?

**Comment by efiring** [comment]
It looks like @ocefpaf needs to take the python 3.6 test out of the travis config first; it's choking because of the lack of scipy for 3.6.

**Comment by efiring** [comment]
#40 is ready to merge, though, and I'm 99% sure #41 is also.  The minor failure in the test is something that was fixed in #40, so it will go away when #40 is merged.

**Comment by wesleybowman** [comment]
Yeah, from what I am seeing, Travis is failing for small things for #41. I will merge that as well. 

> /home/travis/miniconda/envs/TEST/lib/python2.7/site-packages/flake8/options/config.py:56: DeprecationWarning: You passed a bytestring as `filenames`. This will not work on Python 3. Use `cp.read_file()` or switch to using Unicode strings across the board.
> 
>   found_files = config.read(files)
> 
> ./tests/test_solve.py:64:5: F841 local variable 'vel' is assigned to but never used
> 
> ./tests/test_solve.py:65:5: F841 local variable 'htmp' is assigned to but never used
> 
> ./tests/test_solve.py:68:5: E303 too many blank lines (2)

Also, sorry for getting to these so late. Moved to the Netherlands recently, so my timezone may be quite different.

**Comment by ocefpaf** [comment]
You can merge. I am adding the proper Python 3.6 dependencies to the
channel. It should pass as soon as I finish that.

**Pull request merged**
