### PR TITLE
Basic testing framework

### PR DESCRIPTION
**Pull request by ocefpaf**
@wesleybowman do not merge this yet!

Before merging I would like to get [travis-ci](https://travis-ci.org/) working for the PRs.

- Do you have a travis-ci account?  (You can login using you GitHub credentials.)
- Can you enable travis for this repository?  (There is a "turn on" switch for that.)

Let me know if you need any help setting this up.

### CODE REVIEW

**Comment by wesleybowman** [comment]
I signed into travis-ci with my github account, and switched the UTide repository on. Let me know if it didn't work.

**Comment by ocefpaf** [comment]
@wesleybowman yes, it is working.  Now I just need to finish configuring a simple test.  I will ping you once I am done so you can merge this.

Thanks!

**Comment by wesleybowman** [comment]
whats the status of this?

**Comment by ocefpaf** [comment]
Sorry @wesleybowman I am travelling now (going to PyCon) and this is not ready yet.  I will try to speed things up once I get in Montreal.

**Comment by wesleybowman** [comment]
No worries! I was just checking to make sure I wasn't missing a pull. Have fun at PyCon!

**Comment by ocefpaf** [comment]
@wesleybowman This is OK to merge now.  Travis is working and the setup should discover the test automatically (unittest, nosetest, and docstring tests).

NB: Right now there isn't any tests, just the framework to add them.  I will add a few in another PR.

**Pull request merged**
