### PR TITLE
Starting a sphinx documentation tree

### PR DESCRIPTION
**Pull request by efiring**
Here is a sphinx tree that we can build on. I included a "strategy" section where we can put notes about what our general approach is.  This is of course open for debate and modification, but the general idea is that the documentation tree works better than a wiki or issues for such strategy discussion.  This is a conclusion reached recently in mpl; the MEPs will go in the docs, not the wiki.

### CODE REVIEW

**Comment by efiring** [comment]
@ocefpaf FYI;  you don't automatically get notifications of PRs here, do you?

**Comment by ocefpaf** [comment]
I clicked on "watch" recently, so yes.  I do get them now.

**Comment by efiring** [comment]
Aha! So that's what that button is for!

**Comment by ocefpaf** [comment]
Glad I can teach you something :wink:

**Pull request merged**
