### PR TITLE
modify and document user interface; use Bunch

### PR DESCRIPTION
**Pull request by efiring**
The original Matlab function arguments are not a good match for
Python's more flexible argument handling capabilities, so I have
sketched out a more pythonic interface for solve and reconstruct,
including the docstrings.  Given that some option names needed
to change, I have made changes freely, opting for longer but
more readable names.

I have also started using the Bunch more widely; a subsequent
step will be to switch much of the internal access from dictionary
style to attribute style--which will look more like the original
Matlab.

### CODE REVIEW

**Comment by efiring** [comment]
See http://currents.soest.hawaii.edu/UTide/html/index.html for the rendered Sphinx docs that go with this PR.  This documentation is an important part of the user interface.

**Comment by efiring** [comment]
@wesleybowman, I think there is a new problem with the confidence interval calculation, and I don't know yet where I introduced it.  Let's not merge this yet; I want to see if I can track it down and fix it first. Take a look at the basic design of the PR, including the docs, though, and let me know if you have any objections.

**Comment by efiring** [comment]
The bug was my fault: I introduced it in 0e948e3.  It's fixed now.  This PR can be merged if you are comfortable with the direction it is moving.  If not, please let me know ASAP.

**Comment by wesleybowman** [comment]
Very nice work. Great cleanup!

**Pull request merged**
